import json
import re
import unicodedata
import urllib.error
import urllib.request
from pathlib import Path

SOURCE_URLS = [
    "https://raw.githubusercontent.com/hermitdave/FrequencyWords/master/content/2018/fr/fr_50k.txt",
    "https://raw.githubusercontent.com/words/an-array-of-french-words/master/index.json",
]
MAX_TOTAL_WORDS = 350_000
MAX_WORDS_PER_SOURCE = 350_000

GAMER_WORDS = """
GG WP EZ GLHF AFK BRB DPS MMO RPG FPS PVP PVE AOE NPC OP HP XP MP
GAMER GAMERS GAMING GAME GAMES GAMEPLAY PLAYER PLAYERS PLAYING PLAYED
MATCH MATCHES ROUND ROUNDS LEVEL LEVELS QUEST QUESTS MISSION MISSIONS
LOBBY SERVER SERVERS PING LAG LATENCY PARTY SQUAD TEAM TEAMS DUO TRIO
CLAN GUILD RAID BOSS BOSSES MOB MOBS ENEMY ENEMIES MONSTER ZOMBIE
CAMPAIGN STORY SANDBOX SURVIVAL BATTLE ROYALE ARENA ARCADE MODE MODES
ONLINE OFFLINE MULTIPLAYER SINGLEPLAYER COOP COOPERATIVE COMPETITIVE
RANK RANKED RANKING RATING ELO LADDER QUEUE MATCHMAKING SCRIM TOURNAMENT
ESPORTS NOOB NEWBIE PRO TRYHARD SWEAT SWEATY CASUAL HARDCORE TOXIC SALTY
RAGE TILT FLAME SMURF SMURFING BOOST BOOSTED BOOSTING CARRY CARRIED
SKILL SKILLS ABILITY ABILITIES BUFF BUFFS NERF NERFS COOLDOWN PASSIVE
ULTIMATE ULT HEAL HEALER HEALING TANK SUPPORT DAMAGE DPS BURST SHIELD
HEALTH ARMOR MANA STAMINA ATTACK DEFENSE DODGE PARRY BLOCK CRIT CRITICAL
COMBO HITBOX HEADSHOT ONESHOT RESPAWN SPAWN DIVE DIVES DIVING DIVEBOMB DEATH KILL KILLS KILLER
KILLING ASSIST SCORE STREAK WINSTREAK VICTORY DEFEAT COMEBACK ACE WIPE
LOOT DROP LOOTBOX CHEST CRATE INVENTORY ITEM ITEMS GEAR EQUIPMENT WEAPON
WEAPONS SWORD BLADE GUN PISTOL RIFLE SHOTGUN SNIPER SCOPE AMMO BULLET
GRENADE BOMB MELEE RANGED SPELL MAGIC POTION ELIXIR CRAFT CRAFTING BUILD
BUILDING BLUEPRINT RESOURCE RESOURCES GATHER FARM FARMING GRIND GRINDING
MATERIAL RECIPE UPGRADE ENCHANT ENCHANTMENT SKIN SKINS COSMETIC COSMETICS
EMOTE OUTFIT AVATAR CHARACTER CHARACTERS CLASS CLASSES LOADOUT PERK BADGE
ACHIEVEMENT TROPHY UNLOCK REWARD BATTLEPASS SEASON SEASONS DAILY WEEKLY
CHALLENGE EVENT EVENTS MAP MAPS MINIMAP WAYPOINT OBJECTIVE CAPTURE CONTROL
DEFEND ESCORT PUSH FLANK CAMP CAMPER CAMPING RUSH ROTATE ROTATION PEEK
QUICKSCOPE NOSCOPE AIM AIMING ACCURACY RECOIL SPRAY RETICLE CROSSHAIR
FRAG FRAGGING CLUTCH SQUADWIPE RANKUP RANKDOWN POINTS CHECKPOINT SAVEPOINT
JUMP DOUBLEJUMP WALLJUMP DASH SLIDE CROUCH SPRINT STEALTH PARKOUR MOVEMENT
PLATFORMER ROGUELIKE ROGUELITE DECKBUILDER STRATEGY SIMULATOR SANDBOX
FIGHTER FIGHTING BRAWLER SHOOTER LOOTER DUNGEON DUNGEONCRAWLER BATTLEFIELD
HITSCAN PROJECTILE DAMAGE DEALER OFFTANK MAIN SUPPORT FLEX ROLE ROLES
PATCH PATCHES UPDATE UPDATES HOTFIX BETA ALPHA EARLYACCESS RELEASE DLC
EXPANSION MOD MODS MODDING GLITCH BUG EXPLOIT CHEAT CHEATER HACK HACKER
AIMBOT WALLHACK SCRIPT MACRO BOT BOTS SERVERLESS DEDICATED HOST HOSTING
DISCORD TWITCH STREAM STREAMER STREAMING CLIP CLIPS HIGHLIGHT REPLAY
SPECTATE SPECTATOR RECORD RECORDING CHAT VOICE VOICECHAT MICROPHONE MUTE
UNMUTE HEADSET CONTROLLER KEYBOARD MOUSE JOYSTICK CONSOLE HANDHELD PC
GAMERTAG USERNAME PROFILE FRIEND FRIENDS INVITE PARTYCHAT TEXTCHAT
PINGED PACKETLOSS SERVERDOWN DISCONNECT DISCONNECTED RECONNECT CRASH
FPSDROP FRAMERATE LOBBYCODE CROSSPLAY CROSSPROGRESSION INPUT LINUX WINDOWS
CHESTPLATE GAUNTLET BOOTS HELMET BACKPACK INVENTORY LOOTING FARMABLE
MVP MVPs TOPFRAG BOTTOMFRAG KDR KD RATIO WINRATE PICKRATE BANRATE META
OFFMETA OVERPOWERED UNDERPOWERED BROKEN BALANCED UNBALANCED PATCHNOTES
NERFED BUFFED REWORK REWORKED MAIN ALT ALTACCOUNT SECONDARY ACCOUNT
RANKEDMATCH CASUALMATCH QUICKPLAY CUSTOMGAME DEATHMATCH TEAMDEATHMATCH
CAPTURETHEFLAG KINGOFTHEHILL PAYLOAD OBJECTIVE MODE ZONECONTROL DOMINATION
LASTSTANDING ELIMINATION ELIMINATED REVIVE REVIVED RESURRECT RESURRECTION
DOWNED KNOCKED FINISHER FINISHING EXECUTE EXECUTION KNOCKBACK STUN STUNNED
ROOT SILENCE SLOW SLOWED IMMUNITY INVULNERABLE VULNERABLE DAMAGEOVER TIME
DOT HEALOVER TIME HOT LIFESTEAL LIFESTEALING CRITRATE CRITDAMAGE COOLDOWNREDUCTION
COOLDOWNRESET MANA REGEN HEALTHREGEN SHIELDREGEN MOVESPEED ATTACKSPEED
CRITBUILD TANKBUILD DPSBUILD HEALBUILD LOADOUT BUILDCRAFTING THEORYCRAFT
MINMAX MINMAXING OPTIMIZE OPTIMIZED OPTIMIZATION SPEEDRUN SPEEDRUNNER
WALKTHROUGH PLAYTHROUGH GUIDE TUTORIAL BEGINNER ADVANCED EXPERT VETERAN
NEWGAMEPLUS NGPLUS PERMADEATH IRONMAN CHECKPOINT SAVELOAD QUICKLOAD AUTOSAVE
GRINDSET FARMED FARMER CAMPED CAMPING SPAWNCAMP SPAWNCAMPER SPAWNTRAP
RUSHER RUSHING PUSHING FLANKING PEAKING ROTATING THIRD PARTY THIRD-PARTY
TEAMMATE TEAMMATES RANDOMS SOLOQUEUE SOLOQ DUOQUEUE TRIOQUEUE SQUADQUEUE
STACKED PREMADE PREMADETEAM FULLSTACK MATCHPOINT OVERTIME SUDDENDEATH
GGWP GGEZ NT WPNT GLHF HF GL NICE TRY WELLPLAYED GOODGAME GOODLUCK HAVEFUN
FF FORFEIT SURRENDER REMATCH RUNBACK REQUEUE AFKCHECK READY UP READYUP
QUEUEING QUEUED MATCHED UNMATCHED WINNER LOSER LOSING WINNING DRAW TIE
REKT OWNED PWNED CLAPPED DIFF GAP SKILLISSUE GITGUD CARRYPOTENTIAL THROW
THROWING THROWER FEED FEEDING FEEDER INT INTING GRIEF GRIEFING TROLL
TROLLING SMURFQUEUE ELOHELL HARDSTUCK PEAK PEAKRANK PERSONALBEST PB
KDA KDAR RANKEDPOINTS MMR SR LP RR RP XPBOOST DOUBLEXP BOOSTER TOKEN
TOKENS CURRENCY COINS GOLD GEMS SHARDS CREDITS STORE SHOP BUNDLE PASS
PREMIUM FREE2PLAY F2P PAY2WIN P2W MICROTRANSACTION COSMETICONLY SKINSALE
DROPCHANCE DROPRATE LOOTTABLE RARE EPIC LEGENDARY MYTHIC COMMON UNCOMMON
UNIQUE EXOTIC ANCIENT PRIMAL RARITY REROLL GACHA PULL SUMMON BANNER
PITY RATEUP DAILYQUEST WEEKLYQUEST DAILIES WEEKLIES BATTLELOG STATS
LEADERBOARD SCOREBOARD MATCHHISTORY RECAP KILLFEED KILLSTREAK MULTIKILL
DOUBLEKILL TRIPLEKILL QUADRAKILL PENTAKILL FIRSTBLOOD ACECLUTCH NINJADISARM
PLANT DEFUSE DEFUSING BOMBPLANT SPIKE SITE RETAKE POSTPLANT PREPLANT
ROTATOR ENTRYFRAG ENTRYFRAGGER LURKER ANCHOR SENTINEL DUELIST INITIATOR
CONTROLLER SMOKES FLASH FLASHBANG MOLLY MOLOTOV UTILITY UTILITIES LINEUP
RECON REVEAL SCAN SCANNER TRAP TRAPPER TRAPS TURRET DRONE ULTPOINT ULTIMATE
ABILITYCHARGE CHARGED SUPER SUPERCHARGE SUPERCHARGED SPECIAL SPECIALMOVE
FINISHER ANIMATION CANCEL CANCELLED CANCELING FRAME FRAMES FRAMEDATA
HITSTUN BLOCKSTUN NEUTRAL ADVANTAGE DISADVANTAGE PUNISH WHIFF WHIFFPUNISH
FOOTIES MIXUP MIXUPS READ READS YOMI TECH TECHING TECHABLE UNTECHABLE
COMBOBREAKER BREAKER JUGGLE LAUNCHER LAUNCH GRAB THROW THROWS THROWSHIMMY
ROLLBACK NETCODE NETPLAY LOBBYFIGHT DESYNC DESYNCHRONIZED LAGSWITCH
TICKRATE SERVERROLLBACK DELAY INPUTLAG ADAPTIVE TRIGGER DEADZONE SENSITIVITY
SENS SENSITIVITIES DPI EDPI MOUSEPAD AIMTRAINER AIMLAB KOVAAKS FLICKTRACKING
TRACKING FLICK SPRAYCONTROL BURSTFIRE TAPFIRE RECOILCONTROL HIPFIRE ADS
ADSING QUICKDRAW NOSCOPING SCOPED UNSCOPED RETICLEPLACEMENT CROSSHAIRPLACEMENT
SPRAYPATTERN BULLETSPREAD SPREAD MOVINGACCURACY RUNANDGUN STRAFE COUNTERSTRAFE
PEEKERSADVANTAGE WIDEPEEK JIGGLEPEEK SHOULDERPEEK OFFANGLE ANGLE HOLDING
ROTATION MACROPLAY MICROPLAY GAMESENSE GAMEKNOWLEDGE MAPKNOWLEDGE AIMDUEL
DUELING OUTPLAY OUTPLAYED HIGHLIGHTS MONTAGE FRAGMOVIE COMPILATION
CONTENTCREATOR YOUTUBER VOD VODREVIEW REVIEW COACH COACHING COACHED
COACHABLE TEAMPLAY COMMS COMMUNICATION CALLOUT CALLOUTS CALLED COMMSCHECK
MICCHECK PUSH-TO-TALK PUSHTOTALK PTT VOIP VOICECOMMS TEAMCHAT ALLCHAT
PROXIMITYCHAT PROXCHAT PROXIMITY VC LFG LFM LFT LF1M LF2M LF3M LOOKINGFORGROUP
LOOKINGFORMATCH LOOKINGFORTEAM CLANWAR CLANWARS GUILDWAR GUILDWARS SCRIMMAGE
SCRIMS TRYOUT TRYOUTS RECRUITMENT RECRUIT TOXICITY REPORT REPORTED BAN BANNED
SUSPENSION SUSPENDED MUTEALL BLOCKED KICK KICKED VOTEKICK VOTEBAN MODERATOR
MODERATION ADMIN ADMINISTRATOR PATCHDAY MAINTENANCE DOWNTIME SERVERSTATUS
ROLLBACKFIX BUGFIX BUGFIXES HOTFIXED PATCHED UPDATED UPDATELOG CHANGELOG
PATCHNOTES NOTES DEV DEVELOPER DEVS COMMUNITY ROADMAP SEASONAL LIMITEDTIME
TIMELIMITED EVENTPASS QUESTLINE PROGRESSION PROGRESS ACCOUNTLEVEL PLAYERLEVEL
ACCOUNT XPLEVEL EXPERIENCE EXPERIENCEPOINTS LEVELUP LEVELING PRESTIGE PRESTIGED
ASCENSION ASCENDED MASTERY MASTERED MASTERYPOINTS SKILLTREE TALENTTREE PERKTREE
UNLOCKABLE UNLOCKED LOCKED REQUIREMENT REQUIREMENTS PREREQUISITE QUESTING
GRINDABLE FARMABLE REPEATABLE DAILYRESET WEEKLYRESET MONTHLYRESET REWARDTRACK
REWARDTRACKER CHALLENGER CHALLENGES COMPLETED COMPLETION OBJECTIVES BONUS
BONUSXP BONUSREWARD DAILYREWARD WEEKLYREWARD LOGINREWARD STREAKREWARD
LOGINSTREAK WINBONUS LOSSBONUS COMEBACKBONUS UNDERDOG MVPVOTE ENDGAME LATEGAME
EARLYGAME MIDGAME ENDGAME LANE LANING JUNGLE JUNGLER TOPLANE MIDLANE BOTLANE
SIDELANE OFFLANE CARRYLANE SAFELANE HARDLANE ROAMER ROAMING GANK GANKING
GANKED COUNTERGANK COUNTERGANKING WARD WARDS WARDING DEWARD DEWARDING
VISION VISIONWARD SENTRYWARD OBSERVERWARD SMOKE SMOKED SMOKING PULL STACKING
DENY DENIED LASTHIT LASTHITTING CREEP CREEPS MINION MINIONS WAVE WAVECLEAR
FARMING LANEFREEZE FREEZE PUSH SPLITPUSH SPLITPUSHING SIEGE SIEGING OBJECTIVE
BARON DRAGON ELDERDRAGON HERALD NASHOR ROSHAN ANCIENTCAMP JUNGLECAMP
BUFFCAMP BLUEBUFF REDBUFF RED BLUE PURPLE ORANGE NEUTRALCREEP NEUTRALCAMP
GOLDDIFF XPDIF EXPDIFF LEVELDIFF ITEMDIFF POWER SPIKE POWERSPIKE COUNTERPICK
COUNTERPICKING DRAFT DRAFTING BANPICK PICKBAN BLINDPICK FLEXPICK FIRSTPICK
LASTPICK FIRSTBAN LASTBAN PHASE PICK ORDERED DRAFTED COMPOSITION TEAMCOMP
SYNERGY COUNTER COUNTERED MATCHUP FAVORABLE UNFAVORABLE WINCON WINCONDITION
MACRO MACROPLAY MICRO MICROPLAY ROTATION TIMING TEMPO ECONOMY ECO FULLBUY
FORCEBUY HALFBUY SAVE ROUND ECOROUND PISTOLROUND BUYROUND BONUSROUND
ANTIECO ANTI-ECO THRIFTY CLUTCHFACTOR GAMEPLAN STRATEGY STRATEGIC TACTIC
TACTICAL EXECUTION EXECUTE SITEHIT FASTHIT DEFAULT LURK LURKING SPLITATTACK
FAKE FAKEOUT BAIT BAITING TRADE TRADING TRADEKILL REFRAG REFRA GAINSPACE
SPACE CONTROL MAPCONTROL TERRITORY ZONING ZONE ZONINGOUT CROSSFIRE CROSSFIRE
ROTATECALL RETAKECALL SAVE SAVEABLE SAVEROUND SAVEGAME EXITFRAG EXITFRAGGING
ECOFRAG ECOFRAGGING STATSBOARD PERFORMANCE BENCHMARK FPSLATENCY STUTTER
STUTTERING FREEZEFRAME FRAMEPACING FRAMECAP VSync VSYNC GSYNC FREESYNC
INPUTBUFFER INPUTBUFFERING BUFFER ROLLBACK ROLLBACKCODE PREDICTION SERVERPREDICTION
CLIENTSIDE SERVERSIDE CLIENT AUTHORITATIVE DESYNCED PREDICTED HITREG HITREGISTRATION
REGISTRATION NETGRAPH PACKET PACKETS PACKETBURST JITTER BANDWIDTH ROUTER
ETHERNET WIFI WIRED CONNECTION CONNECTIVITY REGION DATACENTER SERVERREGION
REGIONLOCK PINGLOCK CROSSREGION LOWPING HIGHPING PINGDIFF LOBBYPING
SERVERPING CLIENTPING CLIENTFPS SERVERFPS FRAMESTIME STABLE STABILITY CRASHED
CRASHING FREEZING HITCHING STALLING LOADING LOADINGSCREEN QUEUESCREEN
MATCHMAKINGRATING RANKEDLADDER COMPETITIVEQUEUE CASUALQUEUE ARCADEQUEUE
CUSTOMLOBBY PRIVATELOBBY PUBLICLOBBY INVITEONLY PASSWORD PROTECTED
KILLJOY ULTIMATECHARGE CHARGE BAR FULLBAR READY ULTREADY ULTTRACK ULTTRACKING
RESOURCEBAR METER SUPERBAR SPECIALBAR BURSTMODE OVERDRIVE OVERDRIVEGAUGE
COMBOCOUNTER DAMAGECOUNTER HITCOUNTER ROUNDCOUNTER TIMER ROUNDSTART ROUNDEND
SETPOINT GAMEPOINT MATCHPOINT TOURNAMENTPOINT BRACKET SEED SEEDED SEEDING
DOUBLEELIMINATION SINGLEELIMINATION SWISSBRACKET ROUNDROBIN GROUPSTAGE
PLAYOFFS FINALS SEMIFINALS QUARTERFINALS GRAND_FINAL GRAND_FINALS MAJOR
MINOR QUALIFIER QUALIFIERS OPENBRACKET CLOSEDQUALIFIER INVITATIONAL LAN
ONLINEQUALIFIER OFFLINEEVENT ARENAEVENT PRIZEPOOL CASHPRIZE SPONSOR SPONSORED
TEAMHOUSE BOOTCAMP SCRIMBLOCK PRACTICE PRACTICEMODE TRAININGMODE FIRINGRANGE
RANGE WARMUP WARMUPMATCH AIMMAP WORKSHOP WORKSHOPMAP CUSTOMMAP COMMUNITYMAP
MODMAP USERMAP USERMADE MAPEDITOR MODTOOLS LEVELEDITOR MODPACK RESOURCEPACK
TEXTUREPACK SHADERPACK CUSTOMSKIN RESKIN RECOLOR SKINMOD MODDED MODPACKED
SERVERMOD PLUGIN PLUGINS ANTICHEAT ANTI-CHEAT VAC EAC BATTLEYE RICOCHET
FAIRPLAY CHEATDETECTION DETECTED BANNABLE BANWAVE BANWAVED CHEATREPORT
REPORTSYSTEM PLAYERREPORTS APPEAL APPEALED APPEALING SUSPENDED PERMABANNED
PERMABAN SOFTBAN SHADOWBAN SHADOWBANNED SMURFDETECTION MATCHMAKER
BOTLOBBY BOTMATCH PVECOOP PVPVE PVPZONE PVEZONE EXTRACTION EXTRACTIONSHOOTER
EXTRACT EXTRACTED EXTRACTING EVAC EVACUATE EVACUATION DROPZONE DROPSHIP
INSERTION INSERTED LANDING HOTDROP HOTDROPPEAK LOOTPATH ROTATIONPATH
SAFEZONE CIRCLE ZONECLOSING ZONECLOSED STORM STORMS SHRINKING ZONETIMER
FINALCIRCLE ENDZONE LASTZONE GAS GASMASK ARMORPLATE PLATES SHIELDCRACK
KNOCKDOWN KNOCKEDDOWN THIRST THIRSTING THIRD-PARTYING THIRDING PINCH
PINCHING WKEY WKEYING RAT RATTLING RATSPOT CAMPING SPOT CRANK CRANKING
BUILD FORTNITEBOX BOXFIGHTING PIECECONTROL PIECE PIECED EDIT EDITING
QUICKEDIT RESET PEACEFUL BUILDING MATERIALS BRICK WOOD METAL STONE
HARVEST HARVESTING PICKAXE GLIDER INVENTORYSLOT LOADOUTDROP SUPPLYDROP
AIRDROP CAREPACKAGE CAREPACKAGES LOADCOUT REBOOT REBOOTCARD REBOOTVAN
REVIVEVAN RESPAWNBEACON BEACON SCANBEACON SURVEYBEACON UAV MINES MINEFIELD
TRAPDOOR TRAPKILL TRAPBUILD SPIKESTRAP JUMPAD LAUNCHPAD BOUNCER BOUNCEPAD
SHOCKWAVE GRAPPLE GRAPPLER ZIPLINE ZIPLINES VEHICLE DRIVING FLYING BOAT
HELICOPTER TANK VEHICLESKIN VEHICLEMOD GARAGE CUSTOMIZATION PRESET PRESETS
RACE RACER RACING TIMEATTACK DRIFT DRIFTING BOOSTPAD CHECKPOINTLAP
LAPTIME PERSONALRECORD WORLDRECORD WR SPEEDRUNNER SPEEDRUNNING GLITCHLESS
ANY_PERCENT ANYPERCENT LOWPERCENT TAS TOOLASSISTED FRAMEPERFECT PIXELPERFECT
RNG RANDOMSEED SEEDEDRUN ROUTE ROUTING ROUTEPLANNING SKIP SKIPPING SEQUENCEBREAK
SEQUENCEBREAKING SOFTLOCK SOFTLOCKED HARDLOCK HARDLOCKED STUCK UNSTUCK RESETRUN
DEATHCOUNT DEATHLESS HITLESS DAMAGeless NOHIT PACIFIST CHALLENGERUN CHALLENGERUNS
IRONMANRUN PERMARUN NUKE TRUEENDING BADENDING MULTIENDING ENDING BOSSFIGHT
BOSSRUSH BOSSROOM MINIBOSS ELITE ELITES ELITEENEMY CHAMPION CHAMPIONS
CHAMPIONPOOL POOL PICKRATE BANRATE WINRATE TIERLIST TIERLISTS S-TIER ATIER
BTIER CTIER DTIER F-TIER SPLUS S-TIER HIGH-TIER LOWTIER TOPTIER UNDERTIER
OVERPOWERED OPERATOR UNDERPOWERED UP OP DOWN TUNED TUNING BALANCEPATCH
BALANCECHANGE META-SHIFT METASHIFT POWER CREEP POWERCREPT POWERCREPTED
CONTENTDROP CONTENTUPDATE PATCHCYCLE SEASONRESET RANKRESET SOFTRESET HARDRESET
PLACEMENTS PLACEMENTMATCH PLACEMENTMATCHES PROVISIONAL PROVISIONALRANK
CALIBRATION CALIBRATIONMATCH PROMOTIONS DEMOTIONS DIVISION DIVISIONS
PROMOTIONMATCH PROMO SERIES PROMOS GRINDRANK RANKGRIND RANKEDGRIND
RANKPROTECTION DEMOTIONSHIELD LOSSFORGIVENESS DODGEQUEUE DODGING QUEUEDODGE
LEAVER LEAVING DESERTER LEAVEBUSTER PENALTY PENALIZED TIMEOUT COOLDOWNPENALTY
SOCIALQUEUE PARTYFINDER GROUPFINDER TEAMFINDER LFGROUP DUO PARTNER DUO-PARTNER
TRIOPARTNER SQUADMATE SQUADMATES STACK FIVE-STACK THREESTACK TWOSTACK
FOURSTACK SOLOQUEUEING ROLEQUEUE FLEXQUEUE AUTOFILL FILLED ROLELOCK
POSITIONS MAINROLE OFFROLE SECONDARYROLE SECONDARYMAIN TOP MAINMID MIDMAIN
ADCMMAIN ADC BOTMAIN BOTTOMMAIN SUPPORTMAIN JGL JG JUNGLEMAIN TOPLANER
MIDLANER BOTLANER ADCMAIN SUPPORTPLAYER JUNGLEPLAYER OFFLANER POS1 POS2 POS3
POS4 POS5 HARD-SUPPORT SOFT-SUPPORT SAFELANE CARRYPLAYER DRAFTPICK
LASTPICKING FIRSTPICKING COUNTERPICKED COUNTERPICKER POCKETPICK COMFORTPICK
SIGNATUREPICK ONE-TRICK ONETRICK ONETRICKPONY OTP MAINSWAP ROLESWAP
LANESWAP MATCHUPKNOWLEDGE WARDHOP INSEC FLASHKICK KICKS KNOCKUP AIRBORNE
DISPLACE DISPLACEMENT FEAR TAUNT CHARM ROOTED SLOWED SILENCED BLINDED
NEARSIGHTED VISIONBLOCK REVEALED STEALTHED INVISIBILITY INVISIBLE CAMOUFLAGE
DETECTOR TRUEVISION TRUESIGHT FOG WARFOG LINEOFSIGHT LOS WALLBANG WALLBANGING
PENETRATION ARMORPEN MAGICRESIST RESISTANCES RESISTANCE REDUCTION PENETRATION
HEALCUT GRIEVOUSWOUNDS ANTIHEAL SHRED ARMORSHRED RESISTSHRED DAMAGEAMP
AMPLIFICATION VULN VULNERABILITY CC CROWD CONTROL HARDCC SOFTCC CROWDCONTROL
CHAINCC CCCHAIN LOCKDOWN SILENCECHAIN INTERRUPT INTERRUPTED CHANNEL CHANNELING
CHANNELLED CAST CASTING INSTANTCAST WINDUP WINDUPTIME ANIMATIONCANCEL
CANCELTECH BUFFERED INPUTREAD INPUTREADS REACTIONTIME REACTION REACT REACTING
PREDICTION PREDICT PREDICTING READABLE UNREADABLE MIXUPGAME MIXUPGAMEPLAY
MINDGAME MINDGAMES BLUFF BLUFFING BAITED BAITABLE PUNISHABLE SAFE UNSAFE
FRAMEADVANTAGE FRAMEGAP GAPPABLE GAPPABLE GAPS FRAME TRAPSTRING FRAMEKILL
FRAMEKILLER TRUECOMBO TRUECOMBOS LINK LINKS LINKCOMBO CHAINCOMBO CANCELCOMBO
RESETCOMBO COMBORESET TOUCHOFDEATH TOD TODCOMBO INFINITE INFINITELOOP
INFINITELOOPING LOOP LOOPING WALLCARRY CORNER CARRIED CORNERCOMBO CORNERTRAP
OKIZEME OKI WAKEUP WAKEUPATTACK WAKEUPTECH TECHROLL ROLLING ROLLTECH DELAYTECH
MEATY MEATYATTACK SAFEJUMP SAFEJUMPING OPTIONSELECT OPTIONSELECTS OS
FUZZYGUARD FUZZYBLOCK CROSSUP CROSSUPS CROSSUNDER HIGH LOW OVERHEAD LOWPROFILE
INVULN INVULNERABILITY FRAME1 FRAMEONE REVERSAL REVERSALS DP DRAGONPUNCH
ANTI-AIR ANTIAIR AA AIRTOAIR AIRCOMBO AIRDASH AIRDASHING AIRRECOVERY RECOVERY
RECOVERYFRAME RECOVERYFRAMES HITCONFIRM HITCONFIRMING CONFIRM CONFIRMATION
PRACTICECOMBO COMBOCHALLENGE TRIALS CHARACTERTRIALS ARCADEMODE STORYMODE
VERSUS VERSUSMODE LOCALCOOP SPLITSCREEN SPLITSCREENCOOP LANPARTY LANPLAY
HOTSEAT COUCHCOOP COUCHGAMING CROSSPLAYABLE CROSSSAVE CLOUDSAVE CLOUDSAVES
BACKUPSAVE NEWGAME PLUS NEWGAMEPLUS SAVEFILE SAVEFILES SLOT SLOTS LOADSCREEN
FASTTRAVEL TELEPORT TELEPORTER PORTAL PORTALS WARP WARPZONE LEVELSELECT
WORLDSELECT MAPSELECT CHARACTERSELECT CHARSELECT PICKSCREEN LOCKIN LOCKEDIN
READYUP READYING LOADOUTSELECT CLASSSELECT OPERATORSELECT CHAMPSELECT
SPAWNSELECT SIDESELECT ATTACKERS DEFENDERS TERRORISTS COUNTERTERRORISTS CT T
ROUNDWIN ROUNDLOSS MATCHWIN MATCHLOSS SERIESWIN SERIESLOSS GAMEWIN GAMELOSS
MAPWIN MAPLOSS SWEEP SWEPT REVERSESWEEP COMEBACKWIN THROWINGGAME THROWN
CHOKE CHOKED CHOKING CLUTCHUP CHOKER CLOSER COMPOSURE MENTAL MENTALRESET
TILTQUEUING LOSINGSTREAK WINSTREAKING GRINDINGSESSION GAMINGSESSION GAMESESSION
NO-LIFE NOLIFE ADDICTED ADDICTION GRINDSET GAMERTIME PLAYSESSION PLAYTIME
HOURSPLAYED ACHIEVEMENTSCORE COMPLETIONIST 100PERCENT COMPLETIONRUN PLATINUM
PLATINUMTROPHY ACHIEVEMENTHUNT TROPHYHUNT TROPHYHUNTER COLLECTIBLE COLLECTIBLES
SECRET SECRETENDING EASTER EASTER EASTER_EGG EASTER_EGGS LORE LOREBOOK CODEX
JOURNAL LOGBOOK BESTIARY COMPENDIUM COLLECTION COLLECTOR COMPLETEDGAME
NEWCONTENT ENDGAMECONTENT POSTGAME POST-GAME ENDGAMELOOP LOOTLOOP FARGAME
SAVER SCUMMING SAVESCUM SAVE SCUMSAVER SCUMRESTORE QUICKSAVE QUICKLOAD
MANUALSAVE CHECKPOINTSAVE RESPAWNPOINT AUTO-RESPAWN AUTORESPAWN REVIVETIMER
BLEEDOUT BLEEDOUTTIMER RESPAWNTIMER DEATHCAM KILLCAM RECAPSCREEN SUMMARYSCREEN
RESULTSCREEN VICTORYSCREEN DEFEATSCREEN MATCHEND POSTMATCH PREMATCH LOADINGBAY
PREGAME DRAFTSCREEN VETO MAPVETO PICKBANPHASE SPECTATORMODE REPLAYMODE
DEMO DEMOS HIGHLIGHTREEL KILLCAMREPLAY DEATHREPLAY SLOWMO SLOWMOTION FREECAM
FREELOOK OBSERVER OBSERVING COACHMODE COACHVIEW BROADCASTER BROADCASTMODE
TOURNAMENTMODE CUSTOMMATCH PRACTICELOBBY PRIVATEGAME CUSTOMMATCHES MATCHSETTINGS
SERVERBROWSER BROWSER SERVERLIST SERVERLISTING FAVORITE FAVORITES FAVORITED
BOOKMARK BOOKMARKED PASSWORDPROTECTED WHITELIST WHITELISTED BLACKLIST
BLACKLISTED KICKVOTE BANVOTE MUTEVOTE MAPVOTE VOTEKICKED VOTEBANNED
VOICEACTIVATION PUSH2TALK P2T MICTEST AUDIOSETTINGS GRAPHICSSETTINGS
KEYBINDS KEYBIND KEYBINDING KEYBINDINGS HOTKEY HOTKEYS BINDS BINDING
MOUSEBIND KEYBOARDMOUSE CONTROLLERSETTINGS GAMEPAD GAMEPADDED ANALOGSTICK
THUMBSTICK STICKDRIFT DRIFTINGSTICK STICKDEADZONE TRIGGERDEADZONE
VIBRATION HAPTICS FEEDBACK RUMBLE FORCEFEEDBACK MOTIONCONTROL GYRO AIMASSIST
AIMASSISTED AIMASSISTING CONTROLLERPLAYER CONSOLEPLAYER PCPLAYER MOBILEPLAYER
MOBILEGAMING CLOUDGAMING REMOTEGAMING STREAMINGGAMES GAMESTREAMING
LATENCYCOMPENSATION INPUTDELAY FRAMEDELAY SCREENSPACE FULLSCREEN WINDOWED
BORDERLESS VSYNC GSYNC FPSCAP FRAMELIMIT REFRESHRATE HZ MONITORREFRESH
REFRESH RATECAP FRAMEGEN FRAMEGENERATION UPSCALING DLSS FSR XESS RAYTRACING
RAYTRACED TEXTURES TEXTUREQUALITY SHADOWQUALITY REFLECTIONS RESOLUTION
RESOLUTIONSCALING RENDERDISTANCE DRAW DISTANCE FIELDVIEW FOV FOVSLIDER
CAMERASHAKE SHAKE MOTIONBLUR BLUR BLOOM CHROMATICABERRATION FILMGRAIN
POSTPROCESSING ANTIALIASING TAA FXAA MSAA SMAA DLAA RENDERER RENDERING
GPU CPU RAM VRAM MEMORY UTILIZATION TEMPERATURE OVERCLOCK UNDERVOLT
DRIVER DRIVERS GRAPHICSDRIVER PATCHDRIVER CRASHREPORT CRASHLOG LOGFILE
CONFIG CONFIGURATION CONFIGS INI CFG SETTINGS OPTIONS ACCESSIBILITY
SUBTITLES CAPTIONS COLORBLINDNESS COLORBLIND MODE SWITCHER HUD HUDLESS
MINIMALHUD CROSSHAIRSETTINGS RETICLESETTINGS SENSITIVITYSETTINGS GAMMA
BRIGHTNESS CONTRAST AUDIO CHATVOLUME MUSICVOLUME MASTER VOLUME MIXER
LANGUAGE LOCALIZATION TRANSLATION SUBTITLESETTINGS REGIONSETTINGS
SERVERSETTINGS CUSTOMSETTINGS DEFAULTSETTINGS PROFILESETTINGS PRESETTINGS
PRESET CONFIGFILE USERCONFIG AUTOEXEC LAUNCHOPTION LAUNCHOPTIONS COMMANDLINE
STEAM STEAMWORKS EPIC EPICGAMES BATTLE NET BATTLENET EA APP UBISOFTCONNECT
GOG ITCH IO XBOX PLAYSTATION NINTENDO SWITCH STEAMDECK DECK VERIFIED
ACHIEVEMENTUNLOCK ACHIEVEMENTNOTIFICATION FRIENDREQUEST FRIENDLIST PARTYINVITE
GAMEINVITE INVITATION INVITED JOIN JOINED JOINING SESSION SESSIONS HOSTED
HOSTMIGRATION LOBBYMIGRATION MIGRATED BACKFILL BACKFILLING DROPSHIPSPAWN
EARLYACCESSGAME FREEWEEKEND OPENBETA CLOSEDBETA CLOSEDALPHA TECHTEST
PUBLICTESTSERVER PTS TESTSERVER PTR PATCHSERVER LIVEBRANCH EXPERIMENTAL
SANDBOXED TESTBUILD BUILDNUMBER VERSION VERSIONING HOTPATCH HOTPATCHED
ROLLINGUPDATE CONTENTPATCH CLIENTPATCH SERVERPATCH REQUIREDUPDATE OPTIONALUPDATE
UPDATEQUEUED DOWNLOADSIZE PRELOAD PRELOADED PRELOADDLC INSTALLATION INSTALLED
UNINSTALL REINSTALL VERIFYFILES FILEINTEGRITY REPAIRFILES CACHECLEAR
SHADERCACHE SHADERCOMPILATION STUTTERFIX COMPATIBILITY MODE COMPATMODE
ANTICHEATERROR AUTHENTICATION AUTHENTICATED TOKEN EXPIRED SESSIONEXPIRED
LOGIN LOGGEDIN LOGOUT SIGNIN SIGNOUT ACCOUNTLINK LINKEDACCOUNT CROSSACCOUNT
PROFILELINK ACCOUNTRECOVERY PASSWORDRESET TWOFA MFA AUTHENTICATOR VERIFIEDACCOUNT
COMMUNITYMARKET MARKETPLACE TRADING TRADEOFFER TRADED TRADEBAN TRADELOCK
INVENTORYVALUE SKINTRADING SKINCOLLECTION SKINCASE OPENCASE CASEOPENING
CRATEOPENING LOOTCRATE LOOTCRATES SKINCASE CASEDROP CASEHARDENED FACTORYNEW
MINIMALWEAR FIELDTESTED WELLWORN BATTLESCARRED FLOAT PATTERN SEED FLOATVALUE
STATTRACKER STATTRAK KILLSCOUNTER SOUVENIR SIGNATURE AUTOGRAPH STICKER PATCH
CHARM WEAPONCHARM KEYCHAIN COLLECTIONSET SETBONUS MATCHINGSET LOADOUTBUILDER
CUSTOMLOADOUT SAVEDLOADOUT FAVORITELOADOUT QUICKSWAP WEAPONSWAP SWAP SPEED
RELOAD RELOADING RELOADCANCEL RELOADANIMATION AMMOCHECK EMPTYMAG MAGAZINE
CLIPSIZE FIREMODE SINGLEFIRE FULLAUTO SEMIAUTO BURSTMODE BOLT ACTION BOLTACTION
LEVERACTION PUMP ACTION PUMPACTION RECOILPATTERN RECOILSPRING SPREADCONTROL
MUZZLEFLASH SUPPRESSOR SILENCER BARREL STOCK GRIP ATTACHMENT ATTACHMENTS
UNDERBARREL OPTIC OPTICS LASER LASERS TACTICAL GADGET GADGETS EQUIPMENT
DEPLOYABLE DEPLOYABLES THROWABLE THROWABLES CONSUMABLE CONSUMABLES HEALINGITEM
SHIELDITEM ARMORITEM GRENADELAUNCHER ROCKETLAUNCHER LAUNCHER EXPLOSIVES
EXPLOSIVE ARROW BOW CROSSBOW THROWINGKNIFE KNIFE DAGGER SPEAR HAMMER AXE
PICKAXE TOOL HARVESTTOOL MELEEWEAPON PRIMARY SECONDARY SIDEARM UTILITYSLOT
WEAPONSLOT INVENTORYSLOT HOTBAR QUICKBAR LOADOUTSLOT BACKPACKSLOT ARMORSLOT
ACCESSORY ACCESSORIES MODSLOT ATTACHMENT SLOT GEM RUNE RUNES TALENT TALENTS
SKILLPOINT SKILLPOINTS ATTRIBUTE ATTRIBUTES STAT STATS STATPOINT STATPOINTS
RESPEC RESETSKILLS SKILLRESET LEVELINGUP EXPERIENCEBAR XPBAR QUESTMARKER
QUESTLOG QUESTTRACKER TRACKEDQUEST PINNEDQUEST QUESTOBJECTIVE SUBQUEST SIDEQUEST
MAINQUEST STORYQUEST DAILYMISSION WEEKLYMISSION CONTRACT CONTRACTS BOUNTY
BOUNTIES HUNT TARGET TARGETED ELIMINATE ELIMINATION ASSASSINATION ESCAPE
ESCAPED SURVIVE SURVIVOR SQUADLEADER TEAMLEADER CAPTAIN CALLER IGL INGAMELDR
SHOTCALLER SHOTCALLING LEADERSHIP ROLECALL ROLESELECT TEAMCOMPOSITION
FORMATION STRATEGYGUIDE BUILDGUIDE MAPGUIDE HERO HEROES LEGEND LEGENDS
OPERATIVE AGENT AGENTS OPERATOR OPERATORS CHAMPION CHAMPIONS CHARACTERCLASS
CHARACTERBUILD CLASSBUILD SKILLBUILD ITEMBUILD RUNESET TALENTBUILD LOADOUTGUIDE
COUNTERGUIDE TIERGUIDE PATCHGUIDE METAANALYSIS DRAFTGUIDE PICKGUIDE BANLIST
TIERLISTMAKER BUILDRATER MATCHUPGUIDE DATABASE WIKI WIKIA GAMEWIKI DATABASE
PATCHWIKI LOREWIKI COMMUNITYWIKI FANDOM GAMEFAQS STEAMGUIDE GUIDEBOOK
STRATEGYBOOK GAMERGUIDE HELP GUIDE HELPME NEEDHELP CARRYME BOOSTME DUOME
PLAYWITHME INVITEME JOINME PARTYUP SQUADUP TEAMUP LETSGO LESGO GG EZ CLUTCH
NICE TRY NICESHOT GOODSHOT CLEAN AIMBOT WALLHACK ESP CHEATING CHEATS
UNDETECTED DETECTED REPORTABLE REPORTING SUSPICIOUS SUS SUSSING HACKUSATION
HACKUSATIONS TOXICCHAT CHATBANNED VOICEBANNED SHADOWMUTED MUTED VOICEMUTED
CHATMUTED BLOCKLIST BLOCKEDPLAYER AVOIDPLAYER AVOIDLIST TRUSTFACTOR
REPUTATION REPUTATIONCHECK LOWPRIO LOWPRIORITY PRIORITYQUEUE PENALTYQUEUE
TIMEOUTED LEAVEPENALTY ABANDONED ABANDONER DESERTERQUEUE AFKQUEUE LEAVERQUEUE
LEAVERBUSTER LOWPRIOQUEUE BEHAVIOR SCORE BEHAVIORSCORE ENDORSEMENT ENDORSEMENTS
COMMEND COMMENDED COMMENDATION REPORTPLAYER PLAYERBEHAVIOR COMMUNITYGUIDELINES
FAIRPLAYPOLICY CODEOFCONDUCT TERMSOFUSE RULES RULEBREAKER RULEBREAKING
SUSPICIOUSPLAYER TOXICPLAYER GRIEFER GRIEFINGPLAYER FEEDINGPLAYER THROWINGPLAYER
TROLLINGPLAYER AFKPLAYER BOTPLAYER SCRIPTED SCRIPTER AIMHACK HACKING
EXPLOITUSER ABUSER BUGABUSER GLITCHABUSER CHEATENGINE TRAINER INJECTOR
INJECTION MEMORYHACK PACKETMANIPULATION LAGSWITCHER DDOS DOS ATTACKER
SERVERATTACK CRASHER CRASHINGSERVER MATCHFIXING WINTRADING BOOSTINGSERVICE
PILOTED ACCOUNTSELLING ACCOUNTSHARING ACCOUNTBOOSTING CARRYSERVICE ELOBOOST
ELOBOOSTER PAIDCARRY COACHBOOST RANKBOOST RANKBOOSTING BOOSTEDACCOUNT
SMURFACCOUNT ALTACCOUNT ALTS ACCOUNT ALT NEWACCOUNT FRESHACCOUNT SECONDACCOUNT
THROWAWAYACCOUNT BURNERACCOUNT MAINACCOUNT REROLLACCOUNT REGIONACCOUNT
REGIONSWAP REGIONCHANGE SERVERCHANGE PLATFORMCHANGE MIGRATION CROSSPROGRESSION
SAVE TRANSFER CLOUDSYNC SYNCED SYNCING BACKUP RESTORE RESTORATION SAVEBUG
CORRUPTSAVE CORRUPTEDSAVE SAVELOSS DATASAVE ACCOUNTDATA PROGRESSIONLOSS
ROLLBACKLOSS RESTOREPOINT CLOUDRESTORE BACKUPRESTORE
"""

FALLBACK_WORDS = """
CHAT CHIEN OISEAU POISSON CHEVAL VACHE MOUTON COCHON LAPIN SOURIS
MAISON JARDIN CUISINE CHAMBRE SALON GARAGE FENETRE PORTE MUR TOIT
TABLE CHAISE LIT ARMOIRE LAMPE MIROIR TAPIS RIDEAU COUSSIN ETAGERE
VOITURE VELO TRAIN AVION BATEAU BUS METRO MOTO CAMION TAXI
SOLEIL LUNE ETOILE NUAGE PLUIE VENT NEIGE ORAGE ARC CIEL
ARBRE FLEUR HERBE FEUILLE RACINE BRANCHE FRUIT LEGUME GRAINE FORET
POMME POIRE BANANE ORANGE FRAISE CERISE RAISIN CITRON MELON ANANAS
PAIN BEURRE FROMAGE LAIT OEUF SUCRE SEL POIVRE HUILE VINAIGRE
ECOLE LIVRE STYLO CAHIER TABLEAU CRAYON GOMME REGLE CARTABLE BUREAU
AMI FAMILLE PARENT ENFANT FRERE SOEUR COUSIN VOISIN COLLEGUE PROFESSEUR
MUSIQUE DANSE CHANSON GUITARE PIANO VIOLON BATTERIE FLUTE CHORALE CONCERT
SPORT FOOTBALL TENNIS NATATION COURSE VELO ESCALADE JUDO BOXE RUGBY
COULEUR ROUGE BLEU VERT JAUNE VIOLET ROSE NOIR BLANC GRIS
MATIN MIDI SOIR NUIT SEMAINE MOIS ANNEE SAISON HIVER ETE
VILLE RUE PLACE PARC PONT TOUR CHATEAU EGLISE MUSEE MARCHE
MER MONTAGNE RIVIERE LAC PLAGE ILE DESERT VALLEE COLLINE FALAISE
TRAVAIL METIER USINE BUREAU MAGASIN HOPITAL BANQUE POSTE FERME ATELIER
ORDINATEUR CLAVIER ECRAN SOURIS INTERNET LOGICIEL RESEAU FICHIER DOSSIER CODE
CUISINIER MEDECIN AVOCAT POMPIER POLICIER FACTEUR BOULANGER ARTISTE PEINTRE ACTEUR
COURAGE BONHEUR AMOUR AMITIE PATIENCE SAGESSE LIBERTE JUSTICE ESPOIR PAIX
VOYAGE VALISE PASSEPORT HOTEL CAMPING TENTE BOUSSOLE CARTE GUIDE AVENTURE
MANGER BOIRE POUVOIR VOULOIR ALLER VENIR FAIRE DIRE VOIR SAVOIR
PENSER TRAVAILLER ETUDIER APPRENDRE CHANTER MARCHER COURIR SAUTER
REUSSIR OUVRIR FERMER ECRIRE LIRE JOUER REGARDER ECOUTER VOYAGER
DECIDER CHERCHER TROUVER PRENDRE DONNER RECEVOIR ENVOYER APPARTENIR
INVENTER PLANIFIER PROTEGER SECOURIR DEPLACER ESSAYER EXPLIQUER
EXAMINER CONSTRUIRE DECOUVRIR FORMULER EVALUER ANALYSER RESPECTER
RESPIRER DORMIR REVEILLER GRANDIR GROSSIR MAIGRIR DEVENIR DEBATTRE
REMPLIR COMPRENDRE SELECTIONNER PARTICIPER COMMANDE
"""


def normalize_word(word: str, min_length: int = 3) -> str | None:
    if not word:
        return None
    cleaned = unicodedata.normalize("NFKD", word).upper()
    cleaned = "".join(ch for ch in cleaned if not unicodedata.combining(ch))
    cleaned = re.sub(r"[^A-Z]", "", cleaned)
    if len(cleaned) < min_length or len(cleaned) > 15:
        return None
    return cleaned


def load_remote_words() -> list[str]:
    words: list[str] = []
    seen: set[str] = set()

    for url in SOURCE_URLS:
        source_count = 0
        try:
            request = urllib.request.Request(
                url,
                headers={"User-Agent": "Mozilla/5.0"},
            )
            with urllib.request.urlopen(request, timeout=15) as response:
                raw = response.read().decode("utf-8", errors="ignore")
        except (urllib.error.URLError, TimeoutError, ValueError):
            continue

        is_json_source = url.endswith(".json")
        if is_json_source:
            try:
                source_words = json.loads(raw)
            except json.JSONDecodeError:
                continue
            if not isinstance(source_words, list):
                continue
            lines = source_words
        else:
            lines = raw.splitlines()

        for line in lines:
            pieces = (
                [line]
                if is_json_source and isinstance(line, str)
                else re.split(r"[^A-ZÀÂÄÉÈÊËÎÏÔÖÙÛÜÇa-zàâäéèêëîïôöùûüç]+", line)
                if isinstance(line, str)
                else []
            )
            for piece in pieces:
                if not piece:
                    continue
                word = normalize_word(piece)
                if word and word not in seen:
                    seen.add(word)
                    words.append(word)
                    source_count += 1
                    if source_count >= MAX_WORDS_PER_SOURCE or len(words) >= MAX_TOTAL_WORDS:
                        break

            if len(words) >= MAX_TOTAL_WORDS:
                break

    return words


def load_fallback_words() -> list[str]:
    words: list[str] = []
    for raw in FALLBACK_WORDS.split():
        word = normalize_word(raw)
        if word:
            words.append(word)
    return words


def load_gamer_words() -> list[str]:
    words: list[str] = []
    for raw in GAMER_WORDS.split():
        word = normalize_word(raw, min_length=2)
        if word:
            words.append(word)
    return words


def build_wordlist(words: list[str]) -> dict[str, list[dict[str, object]]]:
    unique_words = list(dict.fromkeys(words))
    by_len: dict[str, list[dict[str, object]]] = {}

    for index, word in enumerate(unique_words):
        length = str(len(word))
        by_len.setdefault(length, []).append({
            "word": word,
            "freq": len(unique_words) - index,
        })

    for length in by_len:
        by_len[length].sort(key=lambda entry: -entry["freq"])

    return by_len


def build_local_language_model(words: list[str]) -> dict[str, object]:
    context_counts: dict[str, int] = {}
    trigram_counts: dict[str, int] = {}

    for word in words:
        padded = f"^^{word}$"
        for index in range(len(padded) - 2):
            context = padded[index:index + 2]
            trigram = padded[index:index + 3]
            context_counts[context] = context_counts.get(context, 0) + 1
            trigram_counts[trigram] = trigram_counts.get(trigram, 0) + 1

    return {
        "version": 1,
        "alphabetSize": 28,
        "wordCount": len(words),
        "contexts": context_counts,
        "trigrams": trigram_counts,
    }


if __name__ == "__main__":
    remote_words = load_remote_words()
    # Les mots de secours restent inclus : ils garantissent quelques entrées
    # même si les sources distantes changent ou deviennent indisponibles.
    words = load_gamer_words() + remote_words + load_fallback_words()
    by_len = build_wordlist(words)
    unique_words = list(dict.fromkeys(words))
    language_model = build_local_language_model(unique_words)

    output_path = Path("wordlist.json")
    with output_path.open("w", encoding="utf-8") as file_obj:
        json.dump(by_len, file_obj, ensure_ascii=False, indent=1)

    model_path = Path("word_model.json")
    with model_path.open("w", encoding="utf-8") as file_obj:
        json.dump(language_model, file_obj, ensure_ascii=False, separators=(",", ":"))

    print("Total mots:", len(unique_words))
    print("N-grammes du modèle local:", len(language_model["trigrams"]))
    print("Longueurs disponibles:", sorted(by_len.keys(), key=int))
